# servrices psql

version: '3.9'

services:
  psql:
    image: postgres:latest
    container_name: psql
    restart: always
    environment:
      POSTGRES_USER: scrapy
      POSTGRES_PASSWORD: scrapy
      POSTGRES_DB: e_commerce
     # access throught docker shell

    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    
